export default [
    {
        num : 1,
        type : '봉지면',
        img : 'item_1',
        brand : '삼양식품',
        title : '바담뽕 120g x 32입',
        beforePrice : 54400,
        price : 29920,
    },
    {
        num : 2,
        type : '디저트/간편식',
        img : 'item_18',
        brand : '삼양식품',
        title : '불닭커리 골라담기(4개)',
        beforePrice : 23000,
        price : 20010,
    },
    {
        num : 3,
        type : '봉지면',
        img : 'item_2',
        brand : '삼양식품',
        title : '짜장불닭볶음면 140g x 16입',
        beforePrice : 27200,
        price : 14960,
    },
    {
        num : 4,
        type : '디저트/간편식',
        img : 'item_19',
        brand : '삼양식품',
        title : '불닭납작당면 155g x 12입',
        beforePrice : 42000,
        price : 33600,
    },
    {
        num : 5,
        type : '디저트/간편식',
        img : 'item_20',
        brand : '삼양식품',
        title : '불닭빈달루커리 170g x 3개',
        beforePrice : 15000,
        price : 14500,
    },
    {
        num : 6,
        type : '디저트/간편식',
        img : 'item_21',
        brand : '삼양식품',
        title : '로제불닭납작당면 169g x 12입',
        beforePrice : 42000,
        price : 35760,
    },
    {
        num : 7,
        type : '봉지면',
        img : 'item_3',
        brand : '삼양식품',
        title : '러블리핫불닭볶음면 140g x 20입',
        beforePrice : 36000,
        price : 31520,
    },
    {
        num : 8,
        type : '봉지면',
        img : 'item_4',
        brand : '삼양식품',
        title : '간짬뽕 140g x 20입',
        beforePrice : 24000,
        price : 20880,
    },
    {
        num : 9,
        type : '봉지면',
        img : 'item_5',
        brand : '삼양식품',
        title : '쇠고기면 리뉴얼 120g x 40입',
        beforePrice : 34000,
        price : 28560,
    },
    {
        num : 10,
        type : '봉지면',
        img : 'item_6',
        brand : '삼양식품',
        title : '코다리볶음면 140g x 32입',
        beforePrice : 48000,
        price : 42000,
    },
    {
        num : 11,
        type : '봉지면',
        img : 'item_7',
        brand : '삼양식품',
        title : '우돈사골곰탕면 110g x 40입',
        beforePrice : 50000,
        price : 42000,
    },
    {
        num : 12,
        type : '봉지면',
        img : 'item_8',
        brand : '삼양식품',
        title : '수타면 120g x 40입',
        beforePrice : 38000,
        price : 31920,
    },
    {
        num : 13,
        type : '봉지면',
        img : 'item_9',
        brand : '삼양식품',
        title : '크림까르보불닭볶음면 140g x 16입',
        beforePrice : 27200,
        price : 23600,
    },
    {
        num : 14,
        type : '봉지면',
        img : 'item_10',
        brand : '삼양식품',
        title : '맛있는라면 해물맛 115g x 20입',
        beforePrice : 24000,
        price : 20300,
    },
    {
        num : 15,
        type : '봉지면',
        img : 'item_11',
        brand : '삼양식품',
        title : 'NEW 짜짜로니 140g x 40입',
        beforePrice : 44000,
        price : 36600,
    },
    {
        num : 16,
        type : '봉지면',
        img : 'item_12',
        brand : '삼양식품',
        title : '나가사끼짬뽕 115g x 40입',
        beforePrice : 40000,
        price : 35000,
    },
    {
        num : 17,
        type : '용기면',
        img : 'item_27',
        brand : '삼양식품',
        title : '불닭볶음면 작은컵 70g x 12입',
        beforePrice : 15600,
        price : 14820,
    },
    {
        num : 18,
        type : '용기면',
        img : 'item_28',
        brand : '삼양식품',
        title : '까르보불닭볶음면 작은컵 80g x 12개',
        beforePrice : 16300,
        price : 15520,
    },
    {
        num : 19,
        type : '용기면',
        img : 'item_29',
        brand : '삼양식품',
        title : '큰컵 삼양라면 110g x 16입',
        beforePrice : 24000,
        price : 21000,
    },
    {
        num : 20,
        type : '용기면',
        img : 'item_30',
        brand : '삼양식품',
        title : '큰컵 뽀끼뽀끼크림라뽀끼 110g x 16입',
        beforePrice : 21600,
        price : 18880,
    },
    {
        num : 21,
        type : '스낵',
        img : 'item_38',
        brand : '삼양식품',
        title : '쌀로별뽀빠이강정 100g x 12입',
        beforePrice : 24000,
        price : 16800,
    },
    {
        num : 22,
        type : '스낵',
        img : 'item_39',
        brand : '삼양식품',
        title : '렌티큘러 별뽀빠이 72g x 24입',
        beforePrice : 22500,
        price : 19700,
    },
    {
        num : 23,
        type : '스낵',
        img : 'item_40',
        brand : '삼양식품',
        title : '불닭으로딱!집게 70g x 8봉',
        beforePrice : 13000,
        price : 10400,
    },
    {
        num : 24,
        type : '디저트/간편식',
        img : 'item_22',
        brand : '삼양식품',
        title : '불닭떡볶이 오리지널 185g x 16입',
        beforePrice : 25600,
        price : 20480,
    },
    {
        num : 25,
        type : '디저트/간편식',
        img : 'item_23',
        brand : '삼양식품',
        title : '마라불닭 납작당면 155.6g x 12입',
        beforePrice : 45000,
        price : 36000,
    },
    {
        num : 26,
        type : '디저트/간편식',
        img : 'item_24',
        brand : '삼양식품',
        title : '불닭렌당커리 170g x 3개',
        beforePrice : 12000,
        price : 10900,
    },
    {
        num : 27,
        type : '디저트/간편식',
        img : 'item_25',
        brand : '삼양식품',
        title : '까르보불닭떡볶이 179g x 16입',
        beforePrice : 40000,
        price : 38900,
    },
    {
        num : 28,
        type : '디저트/간편식',
        img : 'item_26',
        brand : '삼양식품',
        title : '로제불닭 떡볶이 183g x 16입',
        beforePrice : 56000,
        price : 45000,
    },
    {
        num : 29,
        type : '용기면',
        img : 'item_31',
        brand : '삼양식품',
        title : '큰컵 짜장불닭볶음면 105g x 16입',
        beforePrice : 15000,
        price : 13010,
    },
    {
        num : 30,
        type : '용기면',
        img : 'item_32',
        brand : '삼양식품',
        title : '큰컵 맛있는라면 112g x 16입',
        beforePrice : 10050,
        price : 9200,
    },
    {
        num : 31,
        type : '봉지면',
        img : 'item_13',
        brand : '삼양식품',
        title : '4가지치즈 불닭볶음면 145g x 32입',
        beforePrice : 54400,
        price : 45690,
    },
    {
        num : 32,
        type : '봉지면',
        img : 'item_14',
        brand : '삼양식품',
        title : '맛있는라면 115g x 40입',
        beforePrice : 35000,
        price : 30500,
    },
    {
        num : 33,
        type : '봉지면',
        img : 'item_15',
        brand : '삼양식품',
        title : '삼양라면 매운맛 120g x 40입 / 오고라 레시피',
        beforePrice : 36000,
        price : 28800,
    },
    {
        num : 34,
        type : '용기면',
        img : 'item_33',
        brand : '삼양식품',
        title : '큰컵 로제불닭볶음면 105g x 16입',
        beforePrice : 16000,
        price : 12800,
    },
    {
        num : 35,
        type : '봉지면',
        img : 'item_16',
        brand : '삼양식품',
        title : '콩나물김치라면 115g x 16입',
        beforePrice : 10500,
        price : 9900,
    },
    {
        num : 36,
        type : '용기면',
        img : 'item_34',
        brand : '삼양식품',
        title : '큰컵 간짬뽕 105g x 16입',
        beforePrice : 25600,
        price : 21500,
    },
    {
        num : 37,
        type : '스낵',
        img : 'item_41',
        brand : '삼양식품',
        title : '짱구 115g x 12입(띠부실 3탄)',
        beforePrice : 18400,
        price : 13600,
    },
    {
        num : 38,
        type : '스낵',
        img : 'item_42',
        brand : '삼양식품',
        title : '페어링바이츠 통밀 베이글칩 50g x 20입',
        beforePrice : 48000,
        price : 45700,
    },
    {
        num : 39,
        type : '용기면',
        img : 'item_35',
        brand : '삼양식품',
        title : '큰컵 짜짜로니 115g x 16입',
        beforePrice : 21600,
        price : 18140,
    },
    {
        num : 40,
        type : '스낵',
        img : 'item_43',
        brand : '삼양식품',
        title : '사또밥 67g*20입',
        beforePrice : 26000,
        price : 22800,
    },
    {
        num : 41,
        type : '용기면',
        img : 'item_36',
        brand : '삼양식품',
        title : '삼양라면 작은컵 65g x 12입',
        beforePrice : 22400,
        price : 19680,
    },
    {
        num : 42,
        type : '봉지면',
        img : 'item_17',
        brand : '삼양식품',
        title : '된장라면 120g x 20입',
        beforePrice : 17000,
        price : 16000,
    },
    {
        num : 43,
        type : '스낵',
        img : 'item_44',
        brand : '삼양식품',
        title : '삼양목장 우유로 만든 밀크전병/딸기전병 4개 세트',
        beforePrice : 48000,
        price : 44500,
    },
    {
        num : 44,
        type : '용기면',
        img : 'item_37',
        brand : '삼양식품',
        title : '큰컵 삼양라면 매운맛110g x 16입',
        beforePrice : 21600,
        price : 18880,
    },
]