export default [
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/202004/evtGtnejSZ6DTPYTupVYcA.jpg',
        brand : '삼양식품',
        title : '도전 불닭볶음면 140g*5입+NEW 핵불닭볶음면 140g*5입',
        beforePrice : 10750,
        price : 9900,
    },
    {
        type : '디저트/간편식',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/f3kE9kyBS7SOcGifoYvh8Q.jpg',
        brand : '삼양식품',
        title : '까르보불닭라볶이 332g (2인분)',
        beforePrice : 5500,
        price : 4500,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/202003/EQZiQKJaTB2FNor5tK4Dpg.jpg',
        brand : '삼양식품',
        title : '도전! 불닭비빔면 140g*5입',
        beforePrice : 5500,
        price : 4400,
    },
    {
        type : '디저트/간편식',
        img : 'https://www.sydeliciousshop.com/resources/goods/202003/bGFhdgEETrSSmFQ!VjWeHw.jpg',
        brand : '삼양식품',
        title : '삼양목장 우유로 만든 밀크만주 23g*3입',
        beforePrice : 2000,
        price : 1900,
    },
    {
        type : '디저트/간편식',
        img : 'https://www.sydeliciousshop.com/resources/goods/201912/ZkJxCJYxQFWVrZrWPDpx2g.jpg',
        brand : '삼양식품',
        title : '불닭소스 200g',
        beforePrice : 5000,
        price : 4500,
    },
    {
        type : '디저트/간편식',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/NGGVBXfwRqiKUvW0XqnALQ.jpg',
        brand : '삼양식품',
        title : '불닭떡볶이 185g * 16입',
        beforePrice : 48000,
        price : 41760,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/202003/azRurSG2QcW0ZetMbR6xTA.jpg',
        brand : '삼양식품',
        title : '짜짜로니 140g * 40입',
        beforePrice : 36000,
        price : 31520,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/202001/WnUvzo5oTRmT5!TxM3XC7g.jpg',
        brand : '삼양식품',
        title : '미트스파게티 불닭볶음면 큰컵 110g',
        beforePrice : 1500,
        price : 1310,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/TgV1soAoTvi8l8_E42WR5Q.jpg',
        brand : '삼양식품',
        title : '나가사끼짬뽕 컵 65g',
        beforePrice : 1050,
        price : 920,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/A6_LczkJS9G0VcPrfJiRWQ.jpg',
        brand : '삼양식품',
        title : '쇠고기면 120g * 40입',
        beforePrice : 28000,
        price : 22400,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/gxlkmIqsTfOQuld3Df6V2w.jpg',
        brand : '삼양식품',
        title : '된장라면 120g * 5입',
        beforePrice : 3500,
        price : 3050,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/202002/usJM8xC3QOyJoEf!aKIvqw.jpg',
        brand : '삼양식품',
        title : '열무비빔면 130g*4입',
        beforePrice : 3600,
        price : 2880,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/202001/39dqTNe!Qi2BNdQcvJuWXg.jpg',
        brand : '삼양식품',
        title : '신림동 백순대볶음면 큰컵 110g',
        beforePrice : 1600,
        price : 1280,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201912/7AY3GGkrSrWqdODYdAmMNg.jpg',
        brand : '삼양식품',
        title : 'NEW 핵불닭볶음면 140g * 10입',
        beforePrice : 10500,
        price : 9900,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201912/JUCXJ7ByS6mEyuRiAidyyA.jpg',
        brand : '삼양식품',
        title : '삼양라면 매운맛 큰컵 110g',
        beforePrice : 1100,
        price : 880,
    },
    {
        type : '스낵',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/S0v7NQZwQWCm5FioImHC_w.jpg',
        brand : '삼양식품',
        title : '별뽀빠이 72g*48입',
        beforePrice : 38400,
        price : 33600,
    },
    {
        type : '스낵',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/7JyZzvAPQhWqQ8ZaxY!pZQ.jpg',
        brand : '삼양식품',
        title : '부셔먹는 라면스낵 불닭 90g * 24입',
        beforePrice : 18000,
        price : 15700,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/j9T58PcOTs!c_4OHkfVqkg.jpg',
        brand : '삼양식품',
        title : '나가사끼짬뽕 컵 65*g*6입',
        beforePrice : 6300,
        price : 5520,
    },
    {
        type : '스낵',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/PkDdbhrdQ8eg_rpjT8W9kQ.jpg',
        brand : '삼양식품',
        title : '사또밥 67g*20입',
        beforePrice : 26000,
        price : 22800,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/L9nyesJRR2Sp1eLB8G6opw.jpg',
        brand : '삼양식품',
        title : '맛있는라면 큰컵 112g*16입',
        beforePrice : 22400,
        price : 19680,
    },
    {
        type : '봉지면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/ph58PokuQYShdmmo0IHC6g.jpg',
        brand : '삼양식품',
        title : '맛있는라면 해물맛 115g * 40입',
        beforePrice : 42000,
        price : 36720,
    },
    {
        type : '스낵',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/GxC!his7Tx6r0a_5xgmmJg.jpg',
        brand : '삼양식품',
        title : '왕짱구 275g*10입',
        beforePrice : 28000,
        price : 24500,
    },
    {
        type : '용기면',
        img : 'https://www.sydeliciousshop.com/resources/goods/201911/BnmM3MT5SwCC3YIKXlGb7A.jpg',
        brand : '삼양식품',
        title : '간짬뽕 큰컵 105g*16입',
        beforePrice : 21600,
        price : 18880,
    },
]